name: build & deploy lambda docker image to ECR

#on: [push]
on:
  repository_dispatch:
    types: [test-event]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Create a repo in us-east-1
        run: |
          aws ecr create-repository --region $REGION2 --repository-name $ECR_REPO_NAME
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION2: 'us-east-1'
          ECR_REPO_NAME: ecr-repo
      - name: Build, tag, image to Amazon
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO_NAME: ecr-repo
          IMAGE_TAG: latest
          REGION1: us-east-2
          REGION2: us-east-1
        run: |
          docker pull 294896388710.dkr.ecr.$REGION1.amazonaws.com/$ECR_REPO_NAME:latest
          docker tag 294896388710.dkr.ecr.$REGION1.amazonaws.com/$ECR_REPO_NAME:latest 294896388710.dkr.ecr.$REGION2.amazonaws.com/$ECR_REPO_NAME:latest
          docker push 294896388710.dkr.ecr.$REGION2.amazonaws.com/$ECR_REPO_NAME:latest
        - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
      - name: Login to AWS ECR
        id: login-ecr-r2
        uses: aws-actions/amazon-ecr-login@v1
      - name: Push image to Amazon
        id: push-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-r2.outputs.registry }}
          ECR_REPO_NAME: ecr-repo
          IMAGE_TAG: latest
          REGION1: us-east-2
          REGION2: us-east-1
        run: |
          docker push 294896388710.dkr.ecr.$REGION2.amazonaws.com/$ECR_REPO_NAME:latest